### ISSUE TITLE
Add progress bar for reconciliation

### ISSUE THREAD

**Issue by jvfe** [jvfe/reconciler#1]
Currently the reconciliation occurs without any indication of progress, different from OpenRefine. It would be nice to give the user some input as to how the process is being handled. 

This would probably require some major refactoring of the post request I use to reconcile, perhaps uploading in chunks and updating a progress bar with tqdm, something that is beyond my skills at the present moment.

**Comment by wetneb** [comment]
It would be a good idea to upload the queries by batches instead of sending the entire dataset in one request. If your requests are too large there are chances that the service just times out.
OpenRefine sends batches of 10 queries per request.

**Comment by jvfe** [comment]
Oh I see! I was thinking of doing something like that, splitting the query into batches of n size and send those. Nice to know OpenRefine already does that. Thanks for the tip!

**Comment by jvfe** [comment]
v0.1.2 (6d8a729) now splits large dataframes and also has a simple progress bar. Thanks.

**Comment by wetneb** [comment]
Wow, that was quick! Thanks a lot :)
