### ISSUE TITLE
Avoid name conflict with module reconcile and function reconcile

### ISSUE THREAD

**Issue by gitonthescene** [jvfe/reconciler#13]
Hi,  I tried monkey patching my fix in #12 to a pip installed version of `reconciler` but it was harder than I expected.  I was able workaround the trouble but it might be worth considering renaming the `reconcile` module.

My first issue was that I was trying to modify `webutils` but because `reconcile`, which uses `webutils`, is imported from `__init__.py`, it’s too late to change once the module is loaded.  My fix was to replace this with a blank `__init__.py`.

The next issue is that [this line](https://github.com/jvfe/reconciler/blob/master/reconciler/__init__.py#L8) replaces the `reconcile` module with the `reconcile` function, my monkey patch which sets `reconciler.reconcile = revonciler.reconcile.reconcile` has trouble when called twice (when running a [Jupyter notebook](https://public.paws.wmcloud.org/User:Gettinwikiwidit/Experiment.ipynb)  for instance).

Might it be a good idea to name the `reconcile` module something like `reconcileImpl` so that the line doesn’t clobber the module with the function? Then this line could be called more than once.  Also the module is visible for debugging.

**Comment by jvfe** [comment]
Huh, that's never really something I worried about as I never had to debug the module itself, usually debugging the function directly. 

Nevertheless, that is a fair point, I'll change it to "main" or something like that. I checked locally that I can change the module name to `main.py` and the `__init__` declaration to `from reconciler.main import reconcile` and this will let you import both the module and the function, without breaking the current API:

```py
# Import the module
from reconciler import main

# Import the function
from reconciler import reconcile
``` 

I'll be sure to apply the change on the next version, thanks for posting this!

**Comment by gitonthescene** [comment]
To be honest if I wasn’t trying to monkey patch my  other issue I never would have paid much attention either.  But when I saw what was happening, it didn’t look like using the same name added much value so I thought I would make the suggestion.

Thanks for having a look at this.
