### ISSUE TITLE
Make reconciliation endpoint configurable

### ISSUE THREAD

**Issue by wetneb** [jvfe/reconciler#4]
Thanks a lot for this wonderful project!

The reconciliation API is supported by many more data sources than Wikidata. Here is a list of public reconciliation endpoints:
https://reconciliation-api.github.io/testbench/

It would be great to make the endpoint configurable, so that the library can be used for other data sources.

**Comment by wetneb** [comment]
I would also change the Python interface to use generic names (such as `id` instead of `qid`) so that it is more natural when used with non-Wikibase sources, perhaps.

**Comment by jvfe** [comment]
Oh, that's great, @wetneb ! I couldn't find much info regarding that, so I just chose the endpoint that seemed the most well maintained hahah. It sure is a great idea, thanks for the tip! I'll try to implement it in the next version, if I have the time. 

And the argument name is a good observation too.

Thanks!

**Comment by MavropaliasG** [comment]
I second this. Well done @jvfe for the great project. If you're looking for ideas in the future, having it be used for any Wikibase instance, not only Wikidata, would be fantastic.

**Comment by jvfe** [comment]
v0.1.1 adds an [argument](https://jvfe.github.io/reconciler/reference/reconcile/) to change the default reconciliation endpoint. Thanks for the input!
