### ISSUE TITLE
Is it possible to reconcile without a type id?

### ISSUE THREAD

**Issue by lubianat** [jvfe/reconciler#5]
I wanted to run a reconciliation regardless of type ID (i.e. any term on Wikidata). 
Do you know if that is possible?

**Comment by jvfe** [comment]
It is, I chose not to do it because when I tried it actually made my code a lot harder to read (lots of if statements).

But I believe there are good enough use cases for omitting type_id, so I'll keep that in mind. 
If you can think of any elegant solution feel free to point that out too.

**Comment by jvfe** [comment]
Code changes would probably have to be done on [webutils.py#L9](https://github.com/jvfe/reconciler/blob/5084ee7847b8b9b931f9b14aa9e513e6c8a783e0/reconciler/webutils.py#L9), refactoring the dict creation and the functions that parse it.
