### ISSUE TITLE
Quer trabalhar com dados abertos?

### ISSUE THREAD

**Issue by JoaoCarabetta** [jvfe/reconciler#7]
Opa João,

estava dando uma olhada nos seus pacotes e eles são beem interessantes.

Eu tenho uma outra iniciativa, o Base dos Dados, https://github.com/basedosdados/mais, que pretende organizar dados públicos num grande banco de dados.

Estamos procurando alguém para estagiar como engenheiro de dados e acho que pode ser interessante pra você:

https://www.linkedin.com/feed/update/urn:li:activity:6736712117942009856/

**Comment by jvfe** [comment]
Olá, João!

Nossa, obrigado pelo elogio e por me notificar desta vaga. Olharei os detalhes mais a fundo e com certeza entrarei em contato pelo email lá na página. Não conheço a iniciativa e vou estudar um pouco a respeito dela também.

Grato!
