### ISSUE TITLE
Support properties by mapping values from additional columns in dataframe

### ISSUE THREAD

**Issue by nickynicolson** [jvfe/reconciler#9]
The reconciliation API supports optional properties which can be used to supply contextual information: https://reconciliation-api.github.io/specs/latest/#structure-of-a-reconciliation-query

Could the reconciler package support supply of a mapping between property names and additional columns in the dataframe, which is then used to build properties in the query object? This is particularly an issue for non-wikidata reconciliation services (as implemented in issue #4).

Example using reconciliation service: http://data1.kew.org/reconciliation/reconcile/IpniName

Dataframe:

|id|scientific_name|genus|species|author
|--|---------------|------|--------|-------|
|1|Quercus robur|Quercus|robur|L

Calling reconcile using just the value in the `scientific_name` column would return 3 potential matches. If we were able to add contextual information about the author via properties, we would return a single match. So when reconciling the column `scientific_name`, we'd like to add extra data from the columns `genus`, `species` and `author` as properties `epithet_1`, `epithet_2` and `publishing_author`:

Query object:

```{json}
{"query":"Quercus robur"
,"properties":[{"p":"epithet_1","pid":"epithet_1","v":"Quercus"}
,{"p":"epithet_2","pid":"epithet_2","v":"robur"}
,{"p":"publishing_author","pid":"publishing_author","v":"L."}]
}
```

Could be implemented by mapping dataframe column name (source of property value) to property id and name:

```{python}
col_prop_mapper={"genus":{"id":"epithet_1","name":"epithet_1"}
"species":{"id":"epithet_2","name":"epithet_2"}
"author":{"id":"publishing_author","name":"publishing_author"}
}
```
... and supplying this mapping as an optional parameter to the `reconcile` function.

**Comment by jvfe** [comment]
This is something I had already thought of doing, just don't have the time to get to it atm, but thank you for your very comprehensive issue! It's great cause it already gives me an example to use for testing purposes.

Currently I use static properties for a reconciliation, e.g.:

```py
# Reconcile against type city (Q515) and items have the country (P17) property equals to Brazil (Q155)
reconciled = reconcile(test_df["City"], type_id="Q515", has_property=("P17", "Q155"))
```

But something I had planned from the start was using a mapping from a dataframe, which seems much more intuitive.

As soon as I'm able to, I'll get to working on this.
